PROJECT_SOURCEFILES += ../libraries/CAN-sim/VirtualCANBus.cpp ../libraries/CAN-sim/VirtualCANBusWrapper.cpp

# Add C++ compilation flags
CXXFLAGS += -std=c++11

# Link the C++ standard library
TARGET_LIBFILES += -lstdc++

include ../Makefile.path
include $(CONTIKI)/Makefile.include
