CONTIKI_PROJECT = coap-observe-server
PLATFORMS_EXCLUDE = sky z1
MODULES += os/net/app-layer/coap
MODULES_REL += ./resources

all: $(CONTIKI_PROJECT)

include ../../Makefile.path
include $(CONTIKI)/Makefile.include
